# Generated by Django 3.1.6 on 2021-02-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0029_auto_20200609_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical',
            name='visa_status',
            field=models.CharField(choices=[('Employer with NOC', 'Employer with NOC'), ('Visit/Tourist', 'Visit/Tourist'), ('Cancelled', 'Cancelled'), ('Spouse/Parent', 'Spouse/Parent')], max_length=90),
        ),
    ]
