# Generated by Django 2.2.1 on 2021-02-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0030_auto_20210208_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs1', models.FileField(upload_to='documents/')),
                ('docs2', models.FileField(upload_to='documents/')),
                ('docs3', models.FileField(upload_to='documents/')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_document', to='payroll.Employee')),
            ],
        ),
    ]
