# Generated by Django 2.2.1 on 2021-02-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0031_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='docs1',
            new_name='document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='docs2',
        ),
        migrations.RemoveField(
            model_name='document',
            name='docs3',
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, choices=[('ID', 'ID'), ('Personal', 'Personal'), ('Employment', 'Employment'), ('Letter', 'Letter'), ('Other', 'Other')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='label',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
