# Generated by Django 2.2.1 on 2021-02-10 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0032_auto_20210209_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave', models.CharField(blank=True, choices=[('Annual', 'Annual'), ('Sick', 'Sick'), ('LWOP', 'LWOP'), ('Special', 'Special')], max_length=60, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=260, null=True)),
                ('approve_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approve_by', to='payroll.Employee')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_leave', to='payroll.Employee')),
            ],
        ),
    ]
