# Generated by Django 2.2.1 on 2021-02-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0033_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='home_country_address',
            new_name='current_address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='home_country_phone',
            new_name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='uae_address',
        ),
    ]
