# Generated by Django 2.2.1 on 2021-02-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0034_auto_20210219_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='bank_name_routing',
            new_name='bank_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='country_birth',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='agent_id',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='employee_unique',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='personal_no_14_digits',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='work_permit_8_digits',
        ),
    ]
