# Generated by Django 2.2.1 on 2021-02-20 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0036_auto_20210220_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='mode_of_payment',
            new_name='bank_ac',
        ),
        migrations.AddField(
            model_name='report',
            name='bank_name',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='payment_method',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash'), ('Other', 'Other')], default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='work_permit',
            field=models.CharField(choices=[('Nepal Can Move', 'Nepal Can Move'), ('Nepal Can Buy', 'Nepal Can Buy'), ('Nepal Can Code', 'Nepal Can Code')], max_length=60),
        ),
    ]
