# Generated by Django 2.2.1 on 2021-02-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0037_auto_20210220_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalpay',
            name='additional',
            field=models.CharField(blank=True, choices=[('Expense Reimbursement', 'Expense Reimbursement'), ('Salary Advance', 'Salary Advance'), ('Bonus', 'Bonus'), ('Overtime/ Holiday Pay', 'Overtime/ Holiday Pay'), ('Other', 'Other')], max_length=60, null=True),
        ),
    ]
