# Generated by Django 2.2.1 on 2021-02-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0038_auto_20210222_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='NepaliDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=60)),
                ('month', models.CharField(max_length=60)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('days', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='month',
        ),
    ]
