# Generated by Django 2.2.1 on 2021-02-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0039_auto_20210228_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nepali_date', to='payroll.NepaliDate'),
        ),
    ]
