# Generated by Django 2.2.1 on 2021-02-28 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0040_timesheet_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalpay',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='additionalpay',
            name='occur',
        ),
        migrations.RemoveField(
            model_name='additionalpay',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='additionalpays',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='additionalpays',
            name='occur',
        ),
        migrations.RemoveField(
            model_name='additionalpays',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='occur',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='deductions',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='deductions',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='deductions',
            name='occur',
        ),
        migrations.RemoveField(
            model_name='deductions',
            name='start_date',
        ),
        migrations.AddField(
            model_name='additionalpay',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nepali_date_additional', to='payroll.NepaliDate'),
        ),
        migrations.AddField(
            model_name='additionalpays',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nepali_date_add', to='payroll.NepaliDate'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nepali_date_deduction', to='payroll.NepaliDate'),
        ),
        migrations.AddField(
            model_name='deductions',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nepali_date_ded', to='payroll.NepaliDate'),
        ),
    ]
