# Generated by Django 2.2.1 on 2021-02-28 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0041_auto_20210228_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processsalary',
            name='salary_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nepali_date_ps', to='payroll.NepaliDate'),
        ),
    ]
