# Generated by Django 2.2.1 on 2021-03-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0042_auto_20210228_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportNepaliDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=60)),
                ('month', models.CharField(max_length=60)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('days', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
