# Generated by Django 2.2.1 on 2021-03-01 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0043_reportnepalidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processsalary',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='processsalary',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='report',
            name='payroll_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nepali_date_report', to='payroll.NepaliDate'),
        ),
        migrations.AlterField(
            model_name='reporttimesheet',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nepali_date_rt', to='payroll.NepaliDate'),
        ),
    ]
