# Generated by Django 2.2.1 on 2021-03-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0044_auto_20210301_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='total',
        ),
    ]
