# Generated by Django 2.2.1 on 2021-03-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0045_remove_timesheet_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='deduction',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
