# Generated by Django 2.2.1 on 2021-03-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0046_auto_20210304_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='deduction',
            field=models.CharField(blank=True, choices=[('Housing Loan', 'Housing Loan'), ('Salary Advance', 'Salary Advance'), ('Traffic Fine', 'Traffic Fine'), ('Loan', 'Loan'), ('Unpaid sick leave', 'Unpaid sick leave'), ('Other', 'Other')], max_length=60, null=True),
        ),
    ]
