# Generated by Django 2.2.1 on 2021-03-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0047_auto_20210304_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deductions',
            old_name='deduction_label',
            new_name='deduction',
        ),
    ]
