# Generated by Django 2.2.1 on 2021-03-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0048_auto_20210304_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductions',
            name='deduction_label',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
