# Generated by Django 2.2.1 on 2021-03-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0049_deductions_deduction_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='partial',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], max_length=60),
        ),
    ]
